#!/bin/sh
# build-mupdf.sh SRCDIR JOBS [MAKEVAR=VALUE...] -- build MuPDF and its C++
# bindings in place. The trailing arguments are make variables chosen by
# cmake/BuildMuPDF.cmake: USE_SYSTEM_LIBS, plus a USE_SYSTEM_<LIB>=no for each
# library it could not find.
#
# Driven by cmake/BuildMuPDF.cmake; see that file for why nothing is installed.
#
# The C++ bindings are generated by scripts/mupdfwrap.py, which needs `libclang`
# and `pipcl`. Neither ships in the MuPDF source release, and MuPDF's own
# `--venv` flag cannot bootstrap them: scripts/wrap/__main__.py imports pipcl at
# module scope, so that import fails before any venv logic runs. So build a venv
# here, install both into it, and pass VENV_FLAG= to stop MuPDF making a second
# one.
set -eu

srcdir=$1
jobs=$2
shift 2

venv=$srcdir/.mubanal-venv
if [ ! -x "$venv/bin/python3" ]; then
    rm -rf "$venv"
    python3 -m venv "$venv"
    "$venv/bin/pip" --quiet install --upgrade pip setuptools
    "$venv/bin/pip" --quiet install libclang pipcl
fi
PATH=$venv/bin:$PATH
export PATH

# HAVE_X11/HAVE_GLUT off keeps the viewer's dependencies out. build=release
# defines NDEBUG, which is what the MUPDF_NDEBUG build option expects.
cd "$srcdir"
exec make -j"$jobs" HAVE_X11=no HAVE_GLUT=no build=release VENV_FLAG= "$@" c++
