# FindMuPDF.cmake -- locate MuPDF headers and libraries.
#
# mubanal uses MuPDF's C++ bindings (libmupdfcpp), which are generated by
# MuPDF's own build and are not packaged by most distributions. Building MuPDF
# from source produces them; see the README.
#
# MuPDF ships no pkg-config file or CMake config, so search the usual prefixes.
# Set MUPDF_ROOT (or -DMUPDF_ROOT=...) to point at a custom build.
#
# Defines: MUPDF_FOUND, MUPDF_INCLUDE_DIRS, MUPDF_LIBRARIES

find_path(MUPDF_INCLUDE_DIR
  NAMES mupdf/fitz.h
  HINTS ${MUPDF_ROOT} ENV MUPDF_ROOT
  PATH_SUFFIXES include
  PATHS /opt/homebrew /usr/local /usr /opt/local)

find_path(MUPDF_CPP_INCLUDE_DIR
  NAMES mupdf/classes.h
  HINTS ${MUPDF_ROOT} ENV MUPDF_ROOT
  PATH_SUFFIXES include platform/c++/include
  PATHS /opt/homebrew /usr/local /usr /opt/local)

find_library(MUPDF_LIBRARY
  NAMES mupdf libmupdf
  HINTS ${MUPDF_ROOT} ENV MUPDF_ROOT
  PATH_SUFFIXES lib lib64 build/release build/shared-release
  PATHS /opt/homebrew /usr/local /usr /opt/local)

find_library(MUPDF_CPP_LIBRARY
  NAMES mupdfcpp libmupdfcpp
  HINTS ${MUPDF_ROOT} ENV MUPDF_ROOT
  PATH_SUFFIXES lib lib64 build/release build/shared-release
  PATHS /opt/homebrew /usr/local /usr /opt/local)

# Distribution builds usually bundle the vendored third-party code (freetype,
# harfbuzz, jbig2dec, ...) into a separate library; source builds may not.
find_library(MUPDF_THIRD_LIBRARY
  NAMES mupdf-third libmupdf-third
  HINTS ${MUPDF_ROOT} ENV MUPDF_ROOT
  PATH_SUFFIXES lib lib64 build/release build/shared-release
  PATHS /opt/homebrew /usr/local /usr /opt/local)

set(MUPDF_LIBRARIES ${MUPDF_CPP_LIBRARY} ${MUPDF_LIBRARY})
if(MUPDF_THIRD_LIBRARY)
  list(APPEND MUPDF_LIBRARIES ${MUPDF_THIRD_LIBRARY})
endif()
set(MUPDF_INCLUDE_DIRS ${MUPDF_INCLUDE_DIR})
if(NOT MUPDF_CPP_INCLUDE_DIR STREQUAL MUPDF_INCLUDE_DIR)
  list(APPEND MUPDF_INCLUDE_DIRS ${MUPDF_CPP_INCLUDE_DIR})
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(MuPDF
  REQUIRED_VARS MUPDF_LIBRARY MUPDF_CPP_LIBRARY MUPDF_INCLUDE_DIR MUPDF_CPP_INCLUDE_DIR
  FAIL_MESSAGE "MuPDF C++ bindings (libmupdfcpp) not found. Most distributions package only the C library, so build MuPDF from source or set MUPDF_ROOT.")

mark_as_advanced(MUPDF_INCLUDE_DIR MUPDF_CPP_INCLUDE_DIR
                 MUPDF_LIBRARY MUPDF_CPP_LIBRARY MUPDF_THIRD_LIBRARY)
